### ISSUE TITLE
spec field type bitlength does not use the full range available

### ISSUE THREAD

**Issue by dskleingeld** [dskleingeld/dataserver#7]
No scaling is introduced, for example:

```
  - BitLength:
      name: Temperature
      min_value: -20.0
      max_value: 50.0
      numb_of_bits: 10
```

results in:
```
  - id: 0
    name: Temperature
    offset: 0
    length: 10
    decode_scale: 1.0
    decode_add: -20.0

```
